export const products = [
  //Alimento
    {
      id: 1,
      name: "Hill's Science Diet, Alimento para Perro Adulto Raza Pequeña, Seco (bulto) 7kg",
      category: "Alimento",
      price: 1080,
      imageUrl: "Alimento-1.png",
      rating: 5,
  },
  {
      id: 2,
      name: "Hill's Science Diet, Alimento para Perro Adulto Raza Pequeña, Seco (bulto) 2kg",
      category: "Alimento",
      price: 513,
      imageUrl: "Alimento-2.png",
      rating: 4,
  },
  {
      id: 3,
      name: "Hill's Science Diet Small Bites, Alimento Seco para Perro Adulto 7+, 2 Kg",
      category: "Alimento",
      price: 540,
      imageUrl: "Alimento-3.png",
      rating: 3,
  },
  {
      id: 4,
      name: "Hill's Science Diet Small & Mini Puppy, Alimento para Perro Cachorro Razas Pequeñas y Mini 5.6Kg",
      category: "Alimento",
      price: 965,
      imageUrl: "Alimento-4.png",
      rating: 4,
  },

  {
    id: 5,
    name: "Hill's Science Diet, Alimento para Gato Adulto 7+ años Indoor, Seco (bulto) 3.2kg",
    category: "Alimento",
    price: 707,
    imageUrl: "Alimento-5.png",
    rating: 4.5,
},

  // Juguetes
    {
      id: 6,
      name: "Paquete Ideal para Jugar y contra el Aburrimiento. Perfecto para Regalo y Cumpleaños",
      category: "Juguetes",
      price: 399,
      imageUrl: "Juguetes-1.png",
      rating: 5,
  },
  {
      id: 7,
      name: "RUISTLI Juguetes para Perro 12 Piezas, Perros Accesorios Interactivo, Juguetes para Perros Ansiosos con Mordedera y Peluches, Juguetes para Perro Grande Cachorros, Cosas para Perros Seguro",
      category: "Juguetes",
      price: 289.00,
      imageUrl: "Juguetes-2.png",
      rating: 4,
  },
  {
      id: 8,
      name: "LUHI Juguete de Peluche para Mascotas Activas, Juguete Interactivo para Perro, Las Bolas de Rebote Interactivas para Perros Inteligentes y Las Bolas Rodantes Automáticas",
      category: "Juguetes",
      price: 149,
      imageUrl: "Juguetes-3.png",
      rating: 3,
  },
  {
      id: 9,
      name: "ZZBIFRJ Pelotas De Goma para Mascotas 3 Pack para Limpiar y Afilar Los Dientes De Las Mascotas, Juguetes para Perro Resistentes a Los Mordiscos para El Adiestramiento De Perros Pequeños y Grandes",
      category: "Juguetes",
      price: 159.00,
      imageUrl: "Juguetes-4.png",
      rating: 4,
  },
  {
      id: 10,
      name: "Menkai Juguetes de Peluche para Perro, Juguete Interactivo para Masticar Pulpo, sin Relleno, con Papel Arrugado, para Perros pequeños a medianos y Grandes, Color Naranja",
      category: "Juguetes",
      price: 108.02,
      imageUrl: "Juguetes-5.png",
      rating: 5,
  },

  // Sofas
    {
      id: 16,
      name: "Jersey suéter para gato y perro, ropa cálida de invierno con capucha (L, Rosado)",
      category: "Ropa",
      price: 167.00,
      imageUrl: "Ropa-1.png",
      rating: 4.5,
  },
  {
      id: 17,
      name: "Abrigo cálido de frutas para perro, sudadera con capucha (XS, Verde)",
      category: "Ropa",
      price: 49.00,
      imageUrl: "Ropa-2.png",
      rating: 4.7,
  },
  {
      id: 18,
      name: "Arnés táctico ajustable para perros, reflectante y de control fácil (S, Amarillo militar)",
      category: "Ropa",
      price: 480.00,
      imageUrl: "Ropa-3.png",
      rating: 4.8,
  },
  {
      id: 19,
      name: "Gorra de béisbol para mascotas, ajustable con orificios para las orejas (S, Azul)",
      category: "Ropa",
      price: 168.00,
      imageUrl: "Ropa-4.png",
      rating: 4.3,
  },
  {
      id: 20,
      name: "Chaqueta de camuflaje cálida para perro y gato, ropa de invierno (3# M)",
      category: "Ropa",
      price: 198.00,
      imageUrl: "Ropa-5.png",
      rating: 4.6,
  },

  // Lamps
  {
    id: 16,
    name: "Modern Lamp",
    category: "Lamp",
    price: 49,
    imageUrl: "lamp-1.png",
    rating: 5,
  },
  {
    id: 17,
    name: "Classic Lamp",
    category: "Lamp",
    price: 59,
    imageUrl: "lamp-2.png",
    rating: 4,
  },
  {
    id: 18,
    name: "Wooden Table Lamp",
    category: "Lamp",
    price: 69,
    imageUrl: "lamp-3.png",
    rating: 3,
  },
  {
    id: 19,
    name: "Industrial Floor Lamp",
    category: "Lamp",
    price: 89,
    imageUrl: "lamp-4.png",
    rating: 5,
  },
  {
    id: 20,
    name: "Vintage Desk Lamp",
    category: "Lamp",
    price: 79,
    imageUrl: "lamp-6.png",
    rating: 4,
  },
];
